version: '3'

services:
    beat:
        build: "."
        container_name: "filebeat"
        restart: "no"
        environment:
            FILEBEAT_CONF_BASE64: "ZmlsZWJlYXQ6CiAgcHJvc3BlY3RvcnM6CiAgICAtIGRvY3VtZW50X3R5cGU6IG5naW54LWVycm9yCiAgICAgIGZpZWxkczoge2hvc3RuYW1lOiB0ZXN0LCBkb2N1bWVudF90eXBlOiBuZ2lueC1lcnJvcn0KICAgICAgaWdub3JlX29sZGVyOiAyNGgKICAgICAgaW5wdXRfdHlwZTogbG9nCiAgICAgIHBhdGhzOiBbL3Zhci9sb2cvbmdpbngvZXJyb3JfdGVzdC5sb2ddCiAgICAgIHRhaWxfZmlsZXM6IHRydWUKICAgIC0gZG9jdW1lbnRfdHlwZTogbmdpbngtYWNjZXNzCiAgICAgIGZpZWxkczoge2hvc3RuYW1lOiB0ZXN0LCBkb2N1bWVudF90eXBlOiBuZ2lueC1hY2Nlc3N9CiAgICAgIGlnbm9yZV9vbGRlcjogMjRoCiAgICAgIGlucHV0X3R5cGU6IGxvZwogICAgICBwYXRoczogWy92YXIvbG9nL25naW54L2FjY2Vzc190ZXN0LmxvZ10KICAgICAgdGFpbF9maWxlczogdHJ1ZQogICAgLSBkb2N1bWVudF90eXBlOiBub2RlanMKICAgICAgZmllbGRzOiB7aG9zdG5hbWU6IHRlc3QsIGRvY3VtZW50X3R5cGU6IG5vZGVqc30KICAgICAgaWdub3JlX29sZGVyOiAyNGgKICAgICAgaW5wdXRfdHlwZTogbG9nCiAgICAgIHBhdGhzOiBbL3Zhci9sb2cvYXBwL3Byb2R1Y3Rpb24ubG9nKl0KICAgICAgdGFpbF9maWxlczogdHJ1ZQoKb3V0cHV0OgogIHJlZGlzOiB7ZGI6IDAsIGhvc3RzOiBbInRlc3Q6NjY2NjYiXSwga2V5OiBmaWxlYmVhdCwgcGFzc3dvcmQ6IHRlc3QsIHRpbWVvdXQ6IDV9Cg=="
